# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):

    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1407, 908)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        widget.setFont(font)
        widget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableView = QtWidgets.QTableView(widget)
        self.tableView.setGeometry(QtCore.QRect(470, 20, 811, 891))
        self.tableView.setObjectName("tableView")
        self.fight_import_button = QtWidgets.QPushButton(widget)
        self.fight_import_button.setGeometry(QtCore.QRect(20, 100, 191, 51))
        self.fight_import_button.setObjectName("fight_import_button")
        self.label1 = QtWidgets.QLabel(widget)
        self.label1.setGeometry(QtCore.QRect(40, 600, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.fight_output_buttom = QtWidgets.QPushButton(widget)
        self.fight_output_buttom.setGeometry(QtCore.QRect(240, 100, 191, 51))
        self.fight_output_buttom.setObjectName("fight_output_buttom")
        self.poomsae_import_button = QtWidgets.QPushButton(widget)
        self.poomsae_import_button.setGeometry(QtCore.QRect(20, 170, 191, 51))
        self.poomsae_import_button.setObjectName("poomsae_import_button")
        self.poomsae_output_button = QtWidgets.QPushButton(widget)
        self.poomsae_output_button.setGeometry(QtCore.QRect(240, 170, 191, 51))
        self.poomsae_output_button.setObjectName("poomsae_output_button")
        self.output_label = QtWidgets.QLabel(widget)
        self.output_label.setGeometry(QtCore.QRect(30, 660, 411, 51))
        self.output_label.setText("")
        self.output_label.setObjectName("output_label")
        self.poomsae_import_button_2 = QtWidgets.QPushButton(widget)
        self.poomsae_import_button_2.setGeometry(QtCore.QRect(20, 240, 191, 51))
        self.poomsae_import_button_2.setObjectName("poomsae_import_button_2")
        self.poomsae_output_button_2 = QtWidgets.QPushButton(widget)
        self.poomsae_output_button_2.setGeometry(QtCore.QRect(240, 240, 191, 51))
        self.poomsae_output_button_2.setObjectName("poomsae_output_button_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(widget)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 320, 411, 261))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setObjectName("calendarWidget")
        self.line = QtWidgets.QFrame(widget)
        self.line.setGeometry(QtCore.QRect(220, 100, 16, 191))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(widget)
        self.line_2.setGeometry(QtCore.QRect(0, 300, 471, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "跆拳道对阵表转换"))
        self.fight_import_button.setText(_translate("widget", "导入竞技对战表"))
        self.label1.setText(_translate("widget", "结果显示："))
        self.fight_output_buttom.setText(_translate("widget", "导出竞技前台表"))
        self.poomsae_import_button.setText(_translate("widget", "导入品势对战表"))
        self.poomsae_output_button.setText(_translate("widget", "导出品势前台表"))
        self.poomsae_import_button_2.setText(_translate("widget", "导入品势成绩"))
        self.poomsae_output_button_2.setText(_translate("widget", "导出品势成绩册"))
