# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'fight.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1407, 908)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        widget.setFont(font)
        widget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableView = QtWidgets.QTableView(widget)
        self.tableView.setGeometry(QtCore.QRect(470, 20, 811, 891))
        self.tableView.setObjectName("tableView")
        self.fight_import_button = QtWidgets.QPushButton(widget)
        self.fight_import_button.setGeometry(QtCore.QRect(10, 50, 191, 51))
        self.fight_import_button.setObjectName("fight_import_button")
        self.fight_num_text = QtWidgets.QTextEdit(widget)
        self.fight_num_text.setGeometry(QtCore.QRect(10, 110, 191, 41))
        self.fight_num_text.setObjectName("fight_num_text")
        self.fight_num_button = QtWidgets.QPushButton(widget)
        self.fight_num_button.setGeometry(QtCore.QRect(210, 110, 121, 41))
        self.fight_num_button.setObjectName("fight_num_button")
        self.output = QtWidgets.QLabel(widget)
        self.output.setGeometry(QtCore.QRect(20, 160, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.output.setFont(font)
        self.output.setObjectName("output")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "跆拳道对阵表转换"))
        self.fight_import_button.setText(_translate("widget", "导入竞技对战表"))
        self.fight_num_text.setHtml(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">输入内容开始行的序号</span></p></body></html>"))
        self.fight_num_button.setText(_translate("widget", "输入确定"))
        self.output.setText(_translate("widget", "结果显示："))


app = QtWidgets.QApplication(sys.argv)
widget = QtWidgets.QWidget()
ui = Ui_widget()
ui.setupUi(widget)
widget.show()
sys.exit(app.exec_())
