# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'import-output.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.9
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#

from PyQt5 import QtCore, QtGui, QtWidgets
# import xlwt
import openpyxl as oxl

from PyQt5.QtWidgets import *
from PyQt5.QtCore import QDate,Qt

def import_sheet(path):
    workBook = oxl.load_workbook(path)
    sheet = workBook.active
    return sheet

def trans_num(lunci) :
    s = str(lunci)
    n = len(s)
    # print(s)
    # print(n)
    out ='c'
    for i in range(2,n) :
        out += s[i]
    # print(out)
    return out
# 转换 轮次 1/4 为 c4
def trans_changci(changci) :
    s = str(changci)
    return s[0],s[1:5]
# 转换场次号 和 场地
def fromat_trans(Sheet,cntWriteRow,Row,changCiCol,lunCiCol,qingNameCol,qingCompanyNameCol,hongNameCol,hongCompanyCol,jiBieCol) :
    # 输入 参数，[列表，行，场次（0），轮次（2），青方姓名（3），青单位（4），红姓名（6），红单位（7），级别（8）]
    import datetime
    lunCi = Sheet.cell(Row,lunCiCol).value
    # print(lunCi)
    # print('lunci L %s  ' %lunCi)
    lunCiOut = '1'
    if lunCi == 'Final' :
        lunCiOut = 'c1'
    else :
        lunCiOut = trans_num(lunCi)

    changDi,chCiId = trans_changci(Sheet.cell(Row,changCiCol).value) # 获取 场地 和 场次号
    list1 = []
    list1.append(cntWriteRow) # 0
    list1.append('') # 1

    list1.append(lunCiOut) # 轮次 2
    list1.append(changDi) # 场地 3
    list1.append(chCiId) # 场次号 4
    list1.append(Sheet.cell(Row,jiBieCol).value) # 级别 5
    list1.append('个人')  # 个人 团体 6
    now = QDate.currentDate()
    list1.append(now.toString(Qt.ISODate))  # 日期 7

    list1.append('') # 8

    list1.append(Sheet.cell(Row,qingNameCol).value) # 青方姓名 9
    list1.append(Sheet.cell(Row,qingCompanyNameCol).value) # 青方单位 10

    list1.append('') # 10

    list1.append(Sheet.cell(Row,hongNameCol).value) # 红方姓名
    list1.append(Sheet.cell(Row,hongCompanyCol).value) # 红方单位

    # 返回格式 ： list[轮次，场地，场次号，级别，个人团体，日期，青方姓名，青方单位，红方姓名，红方单位]
    return list1
# 返回格式 ： list[轮次(2)，场地(3)，场次号(4)，级别5，个人团体6，日期7，青方姓名9，青方单位10，红方姓名12，红方单位13]
# 输入 参数，[列表，行，场次（0），轮次（2），青方姓名（3），青单位（4），红姓名（6），红单位（7），级别（8）]



# NEED : 0(bisaixuhao) 2(lunci) 3(changdi) 4(chngdiho)
# 5(jibie) 6(gerentuanti) 7(riqi) 9(qingfangxinming)
# 10(qingfangdanwei) 12(hongfangxinming) 13(hongfangdanwei)

def write_execl(sheetSource):
    # print(1)
    # sheetSource = import_sheet()
    listTitle =['bisaixuhao','zonglunci','lunci','changdi','chngdiho','jibie','gerentuanti','riqi','qingfangbianhao','qingfangxinming','qingfangdanwei','hongfangbianhao','hongfangxinming','hongfangdanwei']
    cntWriteRow = 0
    sheetName = sheetSource.cell(1,1).value
    outBook = oxl.Workbook()
    outSheet = outBook.active
    outSheet.title = sheetName
    # outSheet = outBook.create_sheet(sheetName)
    startReadRow = 1






    # print(2)
    # for i in range(len(listTitle) ) :
    #     print(3)
    #     print(listTitle)
    #     print(outSheet.cell(row=cntWriteRow,column=i,value=listTitle[i]))
    outSheet.append(listTitle)
    cntWriteRow += 1
    Mxrow = sheetSource.max_row + 1
    now = QDate.currentDate()
    date = now.toString(Qt.ISODate)
    print(3)
    for startReadRow in range(1,Mxrow):
        # judge the startReadRow about  information
        # by -VS-
        # print(sheetSource.cell(startReadRow, 6).value)
        if sheetSource.cell(startReadRow,6).value != None :
            break
    print(startReadRow)

    for i in range(startReadRow,Mxrow) :

        list1 = fromat_trans(sheetSource,cntWriteRow,i,1,3,4,5,7,8,9)
        outSheet.append(list1)
        # outSheet.write(cntWriteRow,0,cntWriteRow)
        # 2 , 3,4,5,6,7,9,10,12,13
        # outSheet.write(cntWriteRow,2,list1[0])
        # outSheet.write(cntWriteRow,3,list1[1])
        # outSheet.write(cntWriteRow,4,list1[2])
        # outSheet.write(cntWriteRow,5,list1[3])
        # outSheet.write(cntWriteRow,6,list1[4])
        # outSheet.write(cntWriteRow,7,list1[5])
        #
        # outSheet.write(cntWriteRow,9,list1[6])
        # outSheet.write(cntWriteRow,10,list1[7])
        #
        # outSheet.write(cntWriteRow,12,list1[8])
        # outSheet.write(cntWriteRow,13,list1[9])
        cntWriteRow += 1

    print('save')
    outBook.save(f'./{date} {sheetName}导出.xlsx')
    print('success!!')
    # QMessageBox.information(QtWidgets.QMainWindow,"消息对话框","success!!",QMessageBox.Yes | QMessageBox.No,QMessageBox.Yes)





class Ui_MainWindow(QtWidgets.QMainWindow):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 393)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.retranslateUi(MainWindow)


        self.fightImport = QtWidgets.QPushButton(self.centralWidget)
        self.fightImport.setGeometry(QtCore.QRect(10, 160, 150, 120)) # 10,160,131,101
        self.fightImport.setObjectName("fightImport")


        self.fightImport.setText("竞技对阵表导入并且导出")
        # MainWindow.setCentralWidget(self.centralWidget)
        # QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 绑定事件
        self.fightImport.clicked.connect(self.openfile)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        # _translate = QtCore.QCoreApplication.translate
        _translate = QtCore.QCoreApplication.translate


        MainWindow.setWindowTitle(_translate("MainWindow", "跆拳道客户端对阵表转换"))


    def openfile(self):
        openfile_name = QFileDialog.getOpenFileName(self,'选择文件','','Excel files(*.xlsx , *.xls)')
        list =[]
        list.append(openfile_name[0])
        sheet = import_sheet(list[0])
        write_execl(sheet)

        # workBook = oxl.load_workbook(list[0])
        # sheet = workBook.active

        # write_execl(sheet)

        # print(list)
        # return list

    # def outputfile(self) :


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)


    MainWindow.show()
    sys.exit(app.exec_())
